const fs = require('fs');
const path = require('path');

class SettingsManager {
  constructor() {
    this.envPath = path.join(__dirname, '.env');
    this.settings = this.loadSettings();
  }

  loadSettings() {
    if (!fs.existsSync(this.envPath)) {
      return {};
    }

    const envContent = fs.readFileSync(this.envPath, 'utf-8');
    const settings = {};

    envContent.split('\n').forEach(line => {
      line = line.trim();
      if (line && !line.startsWith('#')) {
        const [key, ...valueParts] = line.split('=');
        if (key) {
          settings[key.trim()] = valueParts.join('=').trim();
        }
      }
    });

    return settings;
  }

  saveSettings(newSettings) {
    // Merge with existing settings
    this.settings = { ...this.settings, ...newSettings };

    // Build .env content
    const lines = [];
    lines.push('# API Keys Configuration');
    lines.push('# Auto-generated by the app - DO NOT commit to git');
    lines.push('');
    
    lines.push('# Hugging Face Token (FREE - required for speaker diarization)');
    lines.push(`HUGGINGFACE_TOKEN=${this.settings.HUGGINGFACE_TOKEN || ''}`);
    lines.push('');
    
    lines.push('# OpenAI API Key (Optional - for LLM post-processing)');
    lines.push(`OPENAI_API_KEY=${this.settings.OPENAI_API_KEY || ''}`);
    lines.push('');
    
    lines.push('# Google Gemini API Key (Optional - for LLM post-processing)');
    lines.push(`GOOGLE_API_KEY=${this.settings.GOOGLE_API_KEY || ''}`);
    lines.push('');
    
    lines.push('# Anthropic Claude API Key (Optional - for LLM post-processing)');
    lines.push(`ANTHROPIC_API_KEY=${this.settings.ANTHROPIC_API_KEY || ''}`);
    lines.push('');
    
    lines.push('# Default Settings');
    lines.push(`DEFAULT_LLM_PROVIDER=${this.settings.DEFAULT_LLM_PROVIDER || 'none'}`);
    lines.push(`DEFAULT_LLM_MODEL=${this.settings.DEFAULT_LLM_MODEL || ''}`);
    lines.push(`DEFAULT_LLM_TEMPLATE=${this.settings.DEFAULT_LLM_TEMPLATE || 'clean'}`);
    lines.push(`DEFAULT_WHISPER_MODEL=${this.settings.DEFAULT_WHISPER_MODEL || 'medium'}`);
    lines.push(`DEFAULT_TRANSCRIPT_FORMAT=${this.settings.DEFAULT_TRANSCRIPT_FORMAT || 'txt'}`);
    lines.push(`MP3_BITRATE=${this.settings.MP3_BITRATE || '128k'}`);

    fs.writeFileSync(this.envPath, lines.join('\n'), 'utf-8');
    
    // Also update process.env for current session
    Object.keys(newSettings).forEach(key => {
      process.env[key] = newSettings[key];
    });

    return true;
  }

  getSettings() {
    return this.settings;
  }

  getSetting(key) {
    return this.settings[key] || '';
  }
}

module.exports = SettingsManager;
